# Generated by Django 3.1.4 on 2020-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201211_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
